# Generated by Django 5.2.8 on 2025-12-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('under_maintenance', 'Under Maintenance'), ('service', 'Validation')], default='operational', max_length=20)),
            ],
        ),
    ]
